spark.sql.catalog.metastore=org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.metastore.catalog-impl=org.apache.iceberg.hive.HiveCatalog
spark.sql.catalog.metastore.uri=thrift://metastore:9083
spark.sql.catalog.metastore.warehouse=s3a://lakehouse/
spark.sql.catalog.metastore.io-impl=org.apache.iceberg.aws.s3.S3FileIO
spark.sql.catalog.metastore.s3.endpoint=http://minio:9000
spark.sql.catalog.metastore.s3.path-style-access=true
spark.sql.catalog.metastore.s3.region=us-east-1

spark.hadoop.fs.s3a.endpoint=http://minio:9000
spark.hadoop.fs.s3a.path.style.access=true
spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem
spark.hadoop.fs.s3a.connection.ssl.enabled=false

spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
spark.eventLog.enabled=true
spark.eventLog.dir=/opt/spark/spark-events
spark.history.fs.logDirectory=/opt/spark/spark-events

# spark.master=spark://spark-master:7077
# spark.eventLog.enabled=true
# spark.eventLog.dir=/opt/spark/spark-events
# spark.history.fs.logDirectory=/opt/spark/spark-events

# spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
# spark.sql.catalog.hadoop_prod=org.apache.iceberg.spark.SparkCatalog
# spark.sql.catalog.hadoop_prod.type=hadoop
# spark.sql.catalog.hadoop_prod.warehouse=hdfs://namenode:8020/lakehouse