connector.name=hive
hive.metastore.uri=thrift://metastore:9083

fs.hadoop.enabled=true
hive.fs.new-directory-permissions=0755
hive.fs.new-file-inherit-ownership=true
hive.dfs.connect.timeout=2s
hive.dfs.connect.max-retries=5
hive.dfs.replication=1

hive.hdfs.authentication.type=NONE
hive.hdfs.impersonation.enabled=true

hive.storage-format=PARQUET
hive.parquet.use-column-names=true