connector.name=iceberg
hive.metastore.uri=thrift://metastore:9083

fs.hadoop.enabled=true
hive.fs.new-directory-permissions=0777
hive.fs.new-file-inherit-ownership=true
hive.dfs.connect.timeout=2s
hive.dfs.connect.max-retries=5
hive.dfs.replication=1
# hive.config.resources=/etc/hadoop/conf/core-site.xml,/etc/hadoop/conf/hdfs-site.xml

hive.hdfs.authentication.type=NONE
hive.hdfs.impersonation.enabled=false

iceberg.catalog.type=hive_metastore
iceberg.register-table-procedure.enabled=true
iceberg.add-files-procedure.enabled=true
iceberg.file-format=PARQUET